### ISSUE TITLE
bahttext(10056518) Is wrong

### ISSUE THREAD

**Issue by narze** [jojoee/bahttext#6]
![image](https://user-images.githubusercontent.com/248741/136814095-9f1c5c76-ff54-4f06-b939-1ccafa0b876f.png)

สิบล้านห้าหมื่นหกพันห้าร้อย~~หนึ่ง~~สิบแปดบาทถ้วน

**Comment by jojoee** [comment]
Thank you so much kub, fixed on https://github.com/jojoee/bahttext/commit/b606788412be2b49f66f41808b22e7754948a3e5

**Comment by jojoee** [comment]
@narze dont close yet 😅 , I found another bug that's related to this issue

**Comment by narze** [comment]
oh 😅

**Comment by jojoee** [comment]
Ok now, it has been fixed. Thank you again for the contribution kub 🙂
